name: Linters

on: 
  pull_request:
  push:
    branches: [ main, development ]

env:
  FORCE_COLOR: 1

jobs:
  eslint:
    name: ESLint
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "18.x"
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: ESLint Report
        run: npx eslint .
        
  stylelint:
    name: Stylelint
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "18.x"
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Stylelint Report
        run: npx stylelint "**/*.{css,scss}"

        